quarkus:
  package:
    jar:
      type: uber-jar
      add-runner-suffix: false
  datasource:
    db-kind: h2
    jdbc:
      url: jdbc:h2:~/.epub-translator/epub-translator
  hibernate-orm:
    database:
      generation: update
