[versions]
deeplJava = "1.12.0"
quarkus = "3.30.1"
kotlin = "2.2.21"

[libraries]
deepl-api = { group = "com.deepl.api", name = "deepl-java", version.ref = "deeplJava"}
quarkus = { group = "io.quarkus", name = "quarkus-universe-bom", version.ref = "quarkus" }
kotlin-stdlib-jdk8 = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }

[plugins]
quarkus = { id = "io.quarkus", version.ref = "quarkus" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }
